//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEntitywithWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTUALITES
    {
        public int ID_ACTUALITE { get; set; }
        public string TITRE { get; set; }
        public string DESCRIPTION { get; set; }
        public string URL_IMAGE { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public System.DateTime DATE_FIN { get; set; }
        public string LINK { get; set; }
        public int ID_UTILISATEUR { get; set; }
        public bool ACTIF { get; set; }
    }
}
