//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEntitywithWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESSE
    {
        public int ID_ADRESSE { get; set; }
        public int ID_UTILISATEUR { get; set; }
        public string LIBELLE_ADRESSE { get; set; }
        public bool ACTIF { get; set; }
        public string NUMERO_RUE { get; set; }
        public string RUE { get; set; }
        public string CODE_POSTAL { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
    }
}
