//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEntitywithWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        public int ID_COMMANDE { get; set; }
        public int ID_UTILISATEUR { get; set; }
        public int ID_ADRESSE { get; set; }
        public System.DateTime DATE_COMMANDE { get; set; }
        public decimal TOTAL_COMMANDE { get; set; }
        public int ID_COMMANDE_STATUS { get; set; }
    }
}
