//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEntitywithWPF.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodtruckEntities : DbContext
    {
        public FoodtruckEntities()
            : base("name=FoodtruckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTUALITES> ACTUALITES { get; set; }
        public virtual DbSet<ADRESSE> ADRESSE { get; set; }
        public virtual DbSet<ALLERGENE> ALLERGENE { get; set; }
        public virtual DbSet<COMMANDE> COMMANDE { get; set; }
        public virtual DbSet<COMMANDE_STATUT> COMMANDE_STATUT { get; set; }
        public virtual DbSet<FACTURE> FACTURE { get; set; }
        public virtual DbSet<FAMILLE_REPAS> FAMILLE_REPAS { get; set; }
        public virtual DbSet<GENRE> GENRE { get; set; }
        public virtual DbSet<LIGNE_COMMANDE> LIGNE_COMMANDE { get; set; }
        public virtual DbSet<LIGNE_FACTURE> LIGNE_FACTURE { get; set; }
        public virtual DbSet<NOTE> NOTE { get; set; }
        public virtual DbSet<PARAMETRAGE> PARAMETRAGE { get; set; }
        public virtual DbSet<PRODUIT> PRODUIT { get; set; }
        public virtual DbSet<PRODUIT_ALLERGENE> PRODUIT_ALLERGENE { get; set; }
        public virtual DbSet<PROFIL> PROFIL { get; set; }
        public virtual DbSet<SOCIETE> SOCIETE { get; set; }
        public virtual DbSet<TYPE_FAMILLE_REPAS> TYPE_FAMILLE_REPAS { get; set; }
        public virtual DbSet<TYPE_REPAS> TYPE_REPAS { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEUR { get; set; }
    }
}
