//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEntitywithWPF.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT
    {
        public int ID_PRODUIT { get; set; }
        public int ID_FAMILLE_REPAS { get; set; }
        public string LIBELLE_PRODUIT { get; set; }
        public string DESCRIPTION { get; set; }
        public int NOMBRE_DE_VENTE { get; set; }
        public decimal PRIX { get; set; }
        public string URL_IMAGE { get; set; }
        public int STOCK { get; set; }
        public string LMMJVSD { get; set; }
        public Nullable<double> MOYENNE_NOTE { get; set; }
        public string UNITE { get; set; }
    }
}
